-- Migration 008: Safe Improvements (Views, Approval Workflow, Audit Log)
-- 1. Add Approval Workflow Columns
ALTER TABLE public.finance_pro_snapshots
ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS approved_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
-- 2. Create View for Latest Snapshots (Simpler Queries)
CREATE OR REPLACE VIEW public.latest_snapshots AS
SELECT DISTINCT ON (ticker) *
FROM public.finance_pro_snapshots
WHERE is_current = true
ORDER BY ticker,
    created_at DESC;
-- 3. Create Audit Log Table
CREATE TABLE IF NOT EXISTS public.snapshot_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    action VARCHAR(20) NOT NULL,
    -- 'create', 'update', 'delete', 'approve'
    profile_id UUID,
    -- Link to snapshot
    user_id VARCHAR(100),
    details JSONB,
    -- Store diff or metadata
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Enable RLS on audit log
ALTER TABLE public.snapshot_audit_log ENABLE ROW LEVEL SECURITY;
-- Allow read access to authenticated users
CREATE POLICY "Allow read access to audit log" ON public.snapshot_audit_log FOR
SELECT USING (auth.role() = 'authenticated');
-- Allow insert access (service role or app logic will handle this)
CREATE POLICY "Allow insert access to audit log" ON public.snapshot_audit_log FOR
INSERT WITH CHECK (true);
-- 4. Create Materialized View for KPI Performance
-- Note: This snapshots performance metrics for fast dashboard loading
CREATE MATERIALIZED VIEW IF NOT EXISTS public.ticker_kpis AS
SELECT s.ticker,
    s.id as snapshot_id,
    (s.assumptions->>'currentPrice')::numeric as current_price,
    (s.assumptions->>'growthRateEPS')::numeric as growth_rate_eps,
    (s.company_info->>'sector')::text as sector,
    (s.company_info->>'securityRank')::text as security_rank,
    s.updated_at
FROM public.finance_pro_snapshots s
WHERE s.is_current = true;
-- Index for the materialized view
CREATE UNIQUE INDEX IF NOT EXISTS idx_ticker_kpis_ticker ON public.ticker_kpis(ticker);
CREATE INDEX IF NOT EXISTS idx_ticker_kpis_sector ON public.ticker_kpis(sector);
-- Comments
COMMENT ON VIEW public.latest_snapshots IS 'Convenience view for fetching the most recent active snapshot for each ticker';
COMMENT ON TABLE public.snapshot_audit_log IS 'History of important actions taken on analysis snapshots';
COMMENT ON MATERIALIZED VIEW public.ticker_kpis IS 'Cached performance metrics for the main KPI dashboard';