#!/bin/bash
# Nettoyage automatique sans confirmation

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo "🗑️  NETTOYAGE EN COURS..."
echo ""

# Backup
BACKUP_DIR="../GOB_BACKUP_DOCS_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp *.md "$BACKUP_DIR/" 2>/dev/null || true
cp *.txt "$BACKUP_DIR/" 2>/dev/null || true

echo -e "${GREEN}✅ Backup créé: $BACKUP_DIR${NC}"
echo ""

# Liste des fichiers à supprimer
FILES=(
  "FINAL_MESSAGE.txt" "MESSAGE_FINAL_ULTIME.txt" "MISSION_COMPLETE.txt"
  "LISEZ_MOI_EN_PREMIER.txt" "LISEZ_MOI_MAINTENANT.md" "ORDRE_DE_LECTURE.txt"
  "RESUME_ULTRA_SIMPLE.txt" "TABLEAU_RECAP.txt" "NAVIGATION_MAP.txt"
  "DIAGRAMME-AUTOMATISATION.txt"
  "SESSION_MARATHON_31OCT_COMPLETE.md" "SESSION_SUMMARY.md"
  "SESSION_SUMMARY_EMMA_COMPREHENSIVE.md" "AUDIT_COMPLET_2025-10-31.md"
  "DASHBOARD_STATUS_REPORT.md" "API_DIAGNOSTIC_REPORT.md"
  "API-VALIDATION-REPORT.md" "VALIDATION_REPORT.md"
  "ACTION-IMMEDIATE-SUPABASE.md" "ACTION-IMMEDIATE-VALIDATION.md"
  "ACTIONS_IMMEDIATES.md" "URGENT_VERCEL_FIX_REQUIRED.md"
  "URGENT-SUPABASE-DIAGNOSTIC.md" "CONFIGURATION-SUPABASE-IMMEDIATE.md"
  "CONFIGURATION-SUPABASE-URGENTE.md"
  "FIX_LOGIN_ERROR.md" "FIX_LOGIN_PATTERN_ERROR_IMMEDIATE.md"
  "FIX_SMS_FOREIGN_KEY.md" "FIX_SUMMARY.md" "FIX_WATCHLIST_ERROR.md"
  "FIX-SERVERLESS-LIMIT.md" "FIX-WATCHLIST-SUPABASE.md" "FMP_API_FIXED.md"
  "CORRECTIONS_APPLIQUEES.md" "CORRECTIONS-DASHBOARD-RESUME.md"
  "STATUS-CORRECTIONS-FINAL.md" "DIAGNOSTIC_SMS_ERROR.md"
  "CALENDAR_INTEGRATION_REPORT.md" "CALENDAR_TEST_REPORT.md"
  "CALENDRIER_EVALUATION_FINALE.md" "PRODUCTION-API-TEST-REPORT.md"
  "RAPPORT-CORRECTIONS-APIS.md" "RAPPORT-TEST-FINAL-APIS.md"
  "RAPPORT-VALIDATION-FINALE.md" "RAPPORT_VALIDATION_FINALE.md"
  "RAPPORT_COHERENCE_SUPABASE.md" "TESTS_SUPABASE_SUMMARY.md"
  "DEPLOYMENT_CHECKLIST.md" "DEPLOYMENT_COMPLETE.md" "DEPLOYMENT_GUIDE.md"
  "DEPLOIEMENT-CALENDRIER-EN-LIGNE.md" "BRANCHES_CLEANUP_README.md"
  "PR_CREATION_GUIDE.md" "PR_DESCRIPTION_NEW_FEATURES.md"
  "PULL_REQUEST_READY.md" "PULL_REQUEST_SMS_INTEGRATION.md"
)

DELETED=0
for file in "${FILES[@]}"; do
  if [ -f "$file" ]; then
    rm "$file"
    echo -e "  ${GREEN}✓${NC} $file"
    ((DELETED++))
  fi
done

echo ""
echo -e "${GREEN}✅ TERMINÉ!${NC}"
echo -e "  • Fichiers supprimés: $DELETED"
echo -e "  • Backup: $BACKUP_DIR"
echo ""
